[build-system]
requires = ["maturin>=1.15,<2.0"]
build-backend = "maturin"

[project]
name = "py-yaml12"
description = "A modern YAML 1.2 parser and emitter for Python, written in Rust."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
authors = [{ name = "Tomasz Kalinowski" }]
maintainers = [{ name = "Tomasz Kalinowski" }]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Free Threading :: 2 - Beta",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Typing :: Typed",
    "Topic :: Software Development :: Libraries",
    "Topic :: Text Processing :: Markup",
]
keywords = ["yaml", "parser", "serializer", "rust", "pyo3", "abi3"]
dynamic = ["version"]

[dependency-groups]
build = ["maturin>=1.15,<2.0"]
test = [
    { include-group = "build" },
    "mypy>=2.3,<3",
    "pyright>=1.1.411,<2",
    "pytest>=9.1,<10",
]
docs = [
    "css-inline>=0.21,<1",
    "great-tables>=0.23,<1",
    "jupyter>=1.1,<2",
    "pandas>=2.3,<4",
    "plotnine>=0.15,<1",
    "pyyaml>=6.0,<7",
    "ruyaml>=0.91,<1",
]
dev = [
    { include-group = "test" },
    { include-group = "docs" },
]

[project.urls]
Homepage = "https://github.com/posit-dev/py-yaml12"
Documentation = "https://posit-dev.github.io/py-yaml12/"
Repository = "https://github.com/posit-dev/py-yaml12"
Issues = "https://github.com/posit-dev/py-yaml12/issues"
