name: Rust Lints

on:
  pull_request:
  push:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  msrv:
    name: Rust 1.83 minimum version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Rust 1.83
        uses: dtolnay/rust-toolchain@1.83.0

      - name: cargo check (--locked)
        run: cargo check --locked

  rust-lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: cargo fmt (check)
        run: cargo fmt --check

      - name: cargo clippy (-D warnings)
        run: cargo clippy --all-targets --all-features -- -D warnings
